import { Paper, Grid, Button } from "@mui/material";
import React, { ChangeEvent, useState } from "react";
import Head from "next/head";
import { AdminLayout } from "../../../layouts";
import { SubmitHandler, useForm } from "react-hook-form";
import { createBlog, CreateBlogDTO } from "../../../apis/blog";
import {
  Controller,
  ControllerRenderProps,
  ControllerFieldState,
  UseFormStateReturn,
} from "react-hook-form";
import dynamic from "next/dynamic";

import "react-quill/dist/quill.snow.css";
import { useRouter } from "next/router";
import { MSG_SUCCESS } from "../../../utils/constants";
import { useSnackbarContext } from "../../../context/SnackbarContext";
import { uploadSingle } from "../../../apis/upload";
const ReactQuill = dynamic(import("react-quill"), { ssr: false });

type Props = {};

export type RenderContentProps = {
  field: ControllerRenderProps<CreateBlogDTO, "content">;
  fieldState: ControllerFieldState;
  formState: UseFormStateReturn<CreateBlogDTO>;
};

const CreateBlog = (props: Props) => {
  const router = useRouter();
  const { show } = useSnackbarContext();
  const [files, setFiles] = useState<FileList | null>(null);
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm<CreateBlogDTO>({
    defaultValues: {
      content: "",
      title: "",
    },
  });

  const onSubmit: SubmitHandler<CreateBlogDTO> = async (data) => {
    try {
      let thumbnail;
      if (files) {
        const formData = new FormData();
        formData.append("image", files[0]);
        const { message, data: dataImage } = await uploadSingle(formData);
        if (message === MSG_SUCCESS) {
          thumbnail = dataImage.secure_url;
        }
      }

      const { message } = await createBlog({
        ...data,
        ...(thumbnail ? { thumbnail } : {}),
      });
      if (message === MSG_SUCCESS) {
        show("Tạo bài viết thành công", "success");
      }
    } catch (error) {
      console.log("CREATE BLOG ERROR::", error);
    }
  };

  const handleBack = () => {
    router.back();
  };

  return (
    <AdminLayout pageTitle="Thêm mới bài viết">
      <>
        <Head>
          <title>Thêm mới bài viết</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Paper sx={{ padding: "16px" }}>
          <div
            style={{ fontSize: "2rem", fontWeight: "600", marginBottom: 16 }}
          >
            Thông tin thêm mới bài viết
          </div>
          <form onSubmit={handleSubmit(onSubmit)}>
            <Grid container rowSpacing={3} columnSpacing={3}>
              <Grid item xs={12}>
                <div className="form-group">
                  {errors.title && errors.title.type === "required" && (
                    <div className="form-error">
                      Tiêu đề không được để trống
                    </div>
                  )}
                  <input
                    type="text"
                    id="title"
                    className="form-control"
                    autoComplete="off"
                    {...register("title", { required: true })}
                  />
                  <label htmlFor="title" className="form-label required">
                    Tiêu đề
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className="form-group">
                  <input
                    type="file"
                    id="thumbnail"
                    className="form-control"
                    autoComplete="off"
                    onChange={(e: ChangeEvent<HTMLInputElement>) =>
                      setFiles(e.target.files)
                    }
                  />
                  <label htmlFor="thumbnail" className="form-label">
                    Ảnh đại diện
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className="form-group">
                  {errors.content && errors.content.type === "validate" && (
                    <div className="form-error">{errors.content.message}</div>
                  )}
                  <Controller
                    control={control}
                    name="content"
                    rules={{
                      validate: (value) => {
                        if (value === "<p><br></p>") {
                          return "Nội dung không được để trống";
                        }
                      },
                    }}
                    render={(data: RenderContentProps) => {
                      return (
                        <>
                          <ReactQuill
                            theme="snow"
                            value={data.field.value}
                            onChange={data.field.onChange}
                            placeholder="Nội dung bài viết"
                            modules={{
                              toolbar: {
                                container: [
                                  ["bold", "italic", "underline", "strike"],
                                  ["blockquote", "code-block"],

                                  [{ header: 1 }, { header: 2 }],
                                  [{ list: "ordered" }, { list: "bullet" }],
                                  [{ script: "sub" }, { script: "super" }],
                                  [{ indent: "-1" }, { indent: "+1" }],
                                  [{ direction: "rtl" }],

                                  [{ size: ["small", false, "large", "huge"] }],
                                  [{ header: [1, 2, 3, 4, 5, 6, false] }],

                                  [{ color: [] }, { background: [] }],
                                  [{ font: [] }],
                                  [{ align: [] }],

                                  ["clean"],
                                ],
                              },
                            }}
                          />
                        </>
                      );
                    }}
                  />
                  <label htmlFor="slug" className="form-label"></label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <Button
                  variant="outlined"
                  color="secondary"
                  onClick={handleBack}
                >
                  Quay lại
                </Button>
                <Button
                  variant="contained"
                  type="submit"
                  style={{ marginLeft: 8 }}
                >
                  Lưu
                </Button>
              </Grid>
            </Grid>
          </form>
        </Paper>
      </>
    </AdminLayout>
  );
};

export default CreateBlog;
