import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { ProductsLayout } from "../../../layouts";

type Props = {};

const ProductDetail = (props: Props) => {
  const router = useRouter();
  const { slug } = router.query;
  return (
    <ProductsLayout totalProducts={12}>
      <>
        <Head>
          <title>Tất cả sản phẩm</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
      {slug}
    </ProductsLayout>
  );
};

export default ProductDetail;
