import { Container, Grid } from "@mui/material";
import Head from "next/head";
import styles from "../../styles/Payment.module.css";
import { useAuthContext } from "../../context/AuthContext";
import { useCartContext } from "../../context/CartContext";
import Image from "next/image";
import Link from "next/link";

type Props = {};

const Payment = (props: Props) => {
  const { profile } = useAuthContext();
  const { cart } = useCartContext();
  return (
    <div>
      <>
        <Head>
          <title>Thanh toán đơn hàng</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
      <Container maxWidth="lg">
        <Grid container>
          <Grid item xs={12} md={8}>
            <h1>Thông tin đặt hàng</h1>
            <Grid container>
              <Grid item xs={12} md={6}>
                <Grid container columnSpacing={2} rowSpacing={2}>
                  <Grid item xs={12}>
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder=" "
                      />
                      <label htmlFor="" className="form-label">
                        Họ tên
                      </label>
                    </div>
                  </Grid>
                  <Grid item xs={12}>
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder=" "
                      />
                      <label htmlFor="" className="form-label">
                        Số điện thoại
                      </label>
                    </div>
                  </Grid>
                  <Grid item xs={12}>
                    <div className="form-group">
                      <select className="form-control" placeholder=" ">
                        <option value="">abc</option>
                        <option value="">abcd</option>
                        <option value="">abcde</option>
                      </select>
                      <label htmlFor="" className="form-label">
                        Tỉnh / Thành phố
                      </label>
                    </div>
                  </Grid>
                  <Grid item xs={12}>
                    <div className="form-group">
                      <select className="form-control" placeholder=" ">
                        <option value="">abc</option>
                        <option value="">abcd</option>
                        <option value="">abcde</option>
                      </select>
                      <label htmlFor="" className="form-label">
                        Quận / Huyện
                      </label>
                    </div>
                  </Grid>
                  <Grid item xs={12}>
                    <div className="form-group">
                      <select className="form-control" placeholder=" ">
                        <option value="">abc</option>
                        <option value="">abcd</option>
                        <option value="">abcde</option>
                      </select>
                      <label htmlFor="" className="form-label">
                        Phường / Xã
                      </label>
                    </div>
                  </Grid>
                  <Grid item xs={12}>
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder=" "
                      />
                      <label htmlFor="" className="form-label">
                        Địa chỉ
                      </label>
                    </div>
                  </Grid>
                </Grid>
              </Grid>
            </Grid>
            <h1>Phương thức thanh toán</h1>
            <Grid container columnSpacing={2} rowSpacing={2}>
              <Grid item xs={12}>
                <div className={styles.radio}>
                  <input
                    type="radio"
                    name="paymentMethod"
                    id="paymentMethod1"
                    hidden
                  />
                  <div className={styles.circle}></div>
                  <label htmlFor="paymentMethod1">
                    Thanh toán khi nhận hàng (COD)
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className={styles.radio}>
                  <input
                    type="radio"
                    name="paymentMethod"
                    id="paymentMethod2"
                    hidden
                  />
                  <div className={styles.circle}></div>
                  <label htmlFor="paymentMethod2">Thanh toán qua Momo</label>
                </div>
              </Grid>
            </Grid>
          </Grid>
          <Grid item xs={12} md={4}>
            <h1>Đơn hàng</h1>
            <ul className={styles.items}>
              {cart.items.map((item: any) => {
                return (
                  <li key={item.productVariant.id} className={styles.item}>
                    <div className={styles.start}>
                      <Image
                        width={64}
                        height={64}
                        priority={true}
                        alt=""
                        src={item.productVariant.product.thumbnail}
                      />
                    </div>
                    <div className={styles.center}>
                      <div className={styles.name}>
                        {item.productVariant.product.name}
                      </div>
                      <div className={styles.variants}>
                        {item.productVariant.variants.map((variant: any) => {
                          return (
                            <div key={variant.id}>
                              {variant.type}: {variant.name}
                            </div>
                          );
                        })}
                      </div>
                    </div>
                    <div className={styles.right}>
                      <div>{item.productVariant.product.price}</div>
                      <div>x{item.quantity}</div>
                      <div className={styles.total}>
                        {item.productVariant.product.price * item.quantity}
                      </div>
                    </div>
                  </li>
                );
              })}
              <li className={styles["first-row"]}>
                <span>Giá gốc</span>
                <span>
                  {cart.items.reduce(
                    (p: number, c: any) =>
                      p + c.productVariant.product.price * c.quantity,
                    0
                  )}
                  đ
                </span>
              </li>
              <li className={styles.row}>
                <span>Giảm giá</span>
                <span>0đ</span>
              </li>
              <li className={styles["last-row"]}>
                <span>Tổng cộng</span>
                <span>
                  {cart.items.reduce(
                    (p: number, c: any) =>
                      p + c.productVariant.product.price * c.quantity,
                    0
                  )}
                  đ
                </span>
              </li>
              <li className={styles.actions}>
                <Link href="/gio-hang">Quay lại giỏ hàng</Link>
                <button>Thanh toán</button>
              </li>
            </ul>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
};

export default Payment;
