import Head from "next/head";
import React from "react";
import { AdminLayout } from "../../layouts";

type Props = {};

const Dashboard = (props: Props) => {
  return (
    <AdminLayout pageTitle="Trang chủ">
      <>
        <Head>
          <title>Trang chủ</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
    </AdminLayout>
  );
};

export default Dashboard;
