import Head from "next/head";
import React from "react";
import { AdminLayout } from "../../../layouts";

type Props = {};

const Accounts = (props: Props) => {
  return (
    <AdminLayout pageTitle="Tài khoản">
      <>
        <Head>
          <title>Quản lý tài khoản</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
    </AdminLayout>
  );
};

export default Accounts;
