import { Grid, Pagination } from "@mui/material";
import Head from "next/head";
import React from "react";
import { getAllProducts } from "../../apis/product";
import { ProductCard } from "../../components";
import { getListProducts } from "../../dummyData";
import { ProductsLayout } from "../../layouts";
import { Product, ResponseItems } from "../../utils/types";

type Props = {
  productData: ResponseItems<Product>;
};

const AllProducts = (props: Props) => {
  const handleSort = (sortBy: string, sortType: string) => {
    console.log(sortBy, sortType);
  };
  return (
    <ProductsLayout onSort={handleSort} totalProducts={16}>
      <>
        <Head>
          <title>Tất cả sản phẩm</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Grid container columnSpacing={2} rowSpacing={2}>
          {props.productData.items.map((product: Product) => {
            return (
              <Grid item xs={12} sm={6} md={4} key={Math.random() + ""}>
                <ProductCard product={product} />
              </Grid>
            );
          })}
          <Grid item xs={12}>
            <Pagination
              count={10}
              sx={{ ul: { justifyContent: "center" } }}
              variant="outlined"
              shape="rounded"
              showLastButton
              showFirstButton
              page={3}
            />
          </Grid>
        </Grid>
      </>
    </ProductsLayout>
  );
};
export async function getStaticProps() {
  const { data } = await getAllProducts();
  return {
    props: {
      productData: data,
    },
  };
}
export default AllProducts;
