import Head from "next/head";
import React from "react";
import { DefaultLayout } from "../../layouts";

type Props = {};

const Register = (props: Props) => {
  return (
    <DefaultLayout>
      <>
        <Head>
          <title>Đăng ký</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
    </DefaultLayout>
  );
};

export default Register;
