import { Button, Grid, Paper } from "@mui/material";
import dynamic from "next/dynamic";
import Head from "next/head";
import { ChangeEvent, useState } from "react";
import { Controller, SubmitHandler, useForm } from "react-hook-form";
import { CreateBlogDTO, getBlogById, updateBlog } from "../../../../apis/blog";
import { AdminLayout } from "../../../../layouts";
import { MSG_SUCCESS } from "../../../../utils/constants";
import { Blog } from "../../../../utils/types";
import { useRouter } from "next/router";
import "react-quill/dist/quill.snow.css";
import { uploadSingle } from "../../../../apis/upload";
import { useSnackbarContext } from "../../../../context/SnackbarContext";
import { RenderContentProps } from "../create";
const ReactQuill = dynamic(import("react-quill"), { ssr: false });

type Props = {
  blog: Blog;
};

const UpdateBlog = ({ blog }: Props) => {
  const router = useRouter();
  const { show } = useSnackbarContext();
  const [files, setFiles] = useState<FileList | null>(null);
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm<CreateBlogDTO>({
    defaultValues: {
      content: blog.content,
      title: blog.title,
    },
  });

  const onSubmit: SubmitHandler<CreateBlogDTO> = async (data) => {
    try {
      let thumbnail;
      if (files) {
        const formData = new FormData();
        formData.append("image", files[0]);
        const { message, data: dataImage } = await uploadSingle(formData);
        if (message === MSG_SUCCESS) {
          thumbnail = dataImage.secure_url;
        }
      }

      const { message } = await updateBlog(blog.id, {
        ...data,
        ...(thumbnail ? { thumbnail } : {}),
      });
      if (message === MSG_SUCCESS) {
        show("Chỉnh sửa bài viết thành công", "success");
      }
    } catch (error) {
      console.log("UPDATE BLOG ERROR::", error);
    }
  };

  const handleBack = () => {
    router.back();
  };

  return (
    <AdminLayout pageTitle="Chỉnh sửa bài viết">
      <>
        <Head>
          <title>Chỉnh sửa bài viết</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Paper sx={{ padding: "16px" }}>
          <div
            style={{ fontSize: "2rem", fontWeight: "600", marginBottom: 16 }}
          >
            Thông tin bài viết
          </div>
          <form onSubmit={handleSubmit(onSubmit)}>
            <Grid container rowSpacing={3} columnSpacing={3}>
              <Grid item xs={12}>
                <div className="form-group">
                  {errors.title && errors.title.type === "required" && (
                    <div className="form-error">
                      Tiêu đề không được để trống
                    </div>
                  )}
                  <input
                    type="text"
                    id="title"
                    className="form-control"
                    autoComplete="off"
                    {...register("title", { required: true })}
                  />
                  <label htmlFor="title" className="form-label required">
                    Tiêu đề
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className="form-group">
                  <input
                    type="file"
                    id="thumbnail"
                    className="form-control"
                    autoComplete="off"
                    onChange={(e: ChangeEvent<HTMLInputElement>) =>
                      setFiles(e.target.files)
                    }
                  />
                  <label htmlFor="thumbnail" className="form-label">
                    Ảnh đại diện
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className="form-group">
                  {errors.content && errors.content.type === "validate" && (
                    <div className="form-error">{errors.content.message}</div>
                  )}
                  <Controller
                    control={control}
                    name="content"
                    rules={{
                      validate: (value) => {
                        if (value === "<p><br></p>") {
                          return "Nội dung không được để trống";
                        }
                      },
                    }}
                    render={(data: RenderContentProps) => {
                      return (
                        <ReactQuill
                          theme="snow"
                          value={data.field.value}
                          onChange={data.field.onChange}
                          placeholder="Nội dung bài viết"
                        />
                      );
                    }}
                  />
                  <label htmlFor="slug" className="form-label"></label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <Button
                  variant="outlined"
                  color="secondary"
                  onClick={handleBack}
                >
                  Quay lại
                </Button>
                <Button
                  variant="contained"
                  type="submit"
                  style={{ marginLeft: 8 }}
                >
                  Lưu
                </Button>
              </Grid>
            </Grid>
          </form>
        </Paper>
      </>
    </AdminLayout>
  );
};

export async function getServerSideProps(context: any) {
  const { id } = context.query;
  const { message, data } = await getBlogById(+id);
  return message === MSG_SUCCESS
    ? {
        props: { blog: data },
      }
    : {
        notFound: true,
      };
}
export default UpdateBlog;
