import { Button, Grid, Paper } from "@mui/material";
import Head from "next/head";
import React, { useEffect, ChangeEvent, useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import {
  createGroupProduct,
  CreateGroupProductDTO,
  getAllGroupProducts,
} from "../../../apis/groupProduct";
import { AdminLayout } from "../../../layouts";
import { MSG_SUCCESS } from "../../../utils/constants";
import { GroupProduct } from "../../../utils/types";
import { useRouter } from "next/router";
import "react-quill/dist/quill.snow.css";
import dynamic from "next/dynamic";
import { privateAxios } from "../../../config/configAxios";
import { createProduct } from "../../../apis/product";
import { uploadSingle } from "../../../apis/upload";

type Props = {};

const AddGRoupProduct = (props: Props) => {
  const router = useRouter();
  const [detail, setDetail] = useState<string>("");
  const [files, setFiles] = useState<FileList | null>(null);
  const [groupProducts, setGroupProducts] = useState<GroupProduct[]>([]);
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<CreateGroupProductDTO>();
  const onSubmit: SubmitHandler<CreateGroupProductDTO> = async (data) => {
    try {
      let url = "";
      if (files) {
        const formData = new FormData();
        formData.append("image", files[0]);
        const { message, data: dataImage } = await uploadSingle(formData);
        if (message === MSG_SUCCESS) {
          console.log("Uploaded file: ", dataImage);
          url = dataImage.secure_url;
        }
      }
      const { message: msg } = await createGroupProduct({
        ...data,
        ...(url !== "" ? { thumbnail: url } : {}),
      });
      if (msg === MSG_SUCCESS) {
        router.push("/admin/nhom-san-pham");
      }
    } catch (error) {
      console.log(error);
    }
  };

  const handleBack = () => {
    router.back();
  };

  useEffect(() => {
    (async () => {
      const { message, data } = await getAllGroupProducts();
      if (message === MSG_SUCCESS) {
        setGroupProducts(data.items);
      }
    })();
  }, []);

  return (
    <AdminLayout pageTitle="Nhóm sản phẩm">
      <>
        <Head>
          <title>Thêm mới nhóm sản phẩm</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Paper sx={{ padding: "16px" }}>
          <div
            style={{ fontSize: "2rem", fontWeight: "600", marginBottom: 16 }}
          >
            Thông tin thêm nhóm mới sản phẩm
          </div>
          <form onSubmit={handleSubmit(onSubmit)}>
            <Grid container rowSpacing={3} columnSpacing={3}>
              <Grid item xs={12}>
                <div className="form-group">
                  {errors.name && errors.name.type === "required" && (
                    <div className="form-error">Tên không được để trống</div>
                  )}
                  <input
                    type="text"
                    id="name"
                    className="form-control"
                    autoComplete="off"
                    {...register("name")}
                  />
                  <label htmlFor="name" className="form-label required">
                    Tên nhóm sản phẩm
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className="form-group">
                  <input
                    type="text"
                    id="slug"
                    className="form-control"
                    autoComplete="off"
                    {...register("slug")}
                  />
                  <label htmlFor="slug" className="form-label">
                    Bí danh
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className="form-group">
                  <input
                    type="text"
                    id="description"
                    className="form-control"
                    autoComplete="off"
                    {...register("description")}
                  />
                  <label htmlFor="description" className="form-label">
                    Mô tả
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <div className="form-group">
                  <input
                    type="file"
                    id="thumbnail"
                    className="form-control"
                    autoComplete="off"
                    onChange={(e: ChangeEvent<HTMLInputElement>) =>
                      setFiles(e.target.files)
                    }
                  />
                  <label htmlFor="thumbnail" className="form-label">
                    Ảnh đại diện
                  </label>
                </div>
              </Grid>
              <Grid item xs={12}>
                <Button
                  variant="outlined"
                  color="secondary"
                  onClick={handleBack}
                >
                  Quay lại
                </Button>
                <Button
                  variant="contained"
                  type="submit"
                  style={{ marginLeft: 8 }}
                >
                  Lưu
                </Button>
              </Grid>
            </Grid>
          </form>
        </Paper>
      </>
    </AdminLayout>
  );
};

export default AddGRoupProduct;
