import Head from "next/head";
import React from "react";
import { AccountLayout } from "../../layouts";

type Props = {};

const RecentView = (props: Props) => {
  return (
    <AccountLayout titleHeading="Sản phẩm đã xem">
      <>
        <Head>
          <title>Xem gần đây</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
    </AccountLayout>
  );
};

export default RecentView;
