import Head from "next/head";
import React from "react";
import { AccountLayout } from "../../layouts";

type Props = {};

const AddressList = (props: Props) => {
  return (
    <AccountLayout titleHeading="Sổ địa chỉ">
      <>
        <Head>
          <title>Sổ địa chỉ</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
    </AccountLayout>
  );
};

export default AddressList;
