import { Container, Grid } from "@mui/material";
import Head from "next/head";
import { getAllProducts } from "../api/product";
import { ProductCard } from "../components";
import { DefaultLayout } from "../layouts";
import styles from "../styles/Home.module.css";
import { Product, ResponseItems } from "../utils/types";

type ProductsProps = {
  products?: Product[];
};
const Products = (props: ProductsProps) => {
  return (
    <Grid container columnSpacing={2} rowSpacing={2}>
      {props.products?.map((product) => {
        return (
          <Grid item xs={12} sm={6} md={4} key={Math.random() + ""}>
            <ProductCard product={product} />
          </Grid>
        );
      })}
    </Grid>
  );
};
type Props = {
  productData: ResponseItems<Product>;
};
export default function Home({ productData }: Props) {
  return (
    <DefaultLayout>
      <>
        <Head>
          <title>Trang chủ</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Container maxWidth="lg">
            <Products products={productData.items} />
          </Container>
        </main>
      </>
    </DefaultLayout>
  );
}
export async function getStaticProps() {
  const { data } = await getAllProducts();
  return {
    props: {
      productData: data,
    },
  };
}
