import Head from "next/head";
import React from "react";
import { AccountLayout } from "../../layouts";
import { Grid, Pagination } from "@mui/material";
import { ProductCard } from "../../components";
import { getListProducts } from "../../dummyData";

type Props = {};
type ProductsProps = {
  products?: any[];
};
const Products = (props: ProductsProps) => {
  return (
    <Grid container columnSpacing={2} rowSpacing={2}>
      {props.products?.map((product) => {
        return (
          <Grid item xs={12} sm={6} lg={4} key={Math.random() + ""}>
            <ProductCard product={product} />
          </Grid>
        );
      })}
      <Grid item xs={12}>
        <Pagination
          count={10}
          sx={{ ul: { justifyContent: "center" } }}
          variant="outlined"
          shape="rounded"
          showLastButton
          showFirstButton
          page={3}
        />
      </Grid>
    </Grid>
  );
};
const Wishlist = (props: Props) => {
  return (
    <AccountLayout titleHeading="Sản phẩm yêu thích">
      <>
        <Head>
          <title>Sản phẩm yêu thích</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Products products={getListProducts(12)} />
        </div>
      </>
    </AccountLayout>
  );
};

export default Wishlist;
