import Head from "next/head";
import React, { useEffect, useState } from "react";
import { AccountLayout } from "../../layouts";
import { Grid, Pagination } from "@mui/material";
import { ProductCard } from "../../components";
import { Product, ResponseItems } from "../../utils/types";
import { getFavoriteProducts } from "../../apis/product";
import { useRouter } from "next/router";
import { MSG_SUCCESS } from "../../utils/constants";

type Props = {};

const Wishlist = (props: Props) => {
  const [productData, setProductData] = useState<ResponseItems<Product>>({
    items: [],
    count: 0,
  });
  const router = useRouter();
  useEffect(() => {
    (async () => {
      try {
        const { message, data } = await getFavoriteProducts(router.query);
        if (message === MSG_SUCCESS) {
          setProductData(data);
        }
      } catch (error) {
        console.log(error);
      }
    })();
  }, [router.query]);
  return (
    <AccountLayout titleHeading="Sản phẩm yêu thích">
      <>
        <Head>
          <title>Sản phẩm yêu thích</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Grid container columnSpacing={2} rowSpacing={2}>
            {productData.items.map((product: Product) => {
              return (
                <Grid item xs={12} sm={6} lg={4} key={Math.random() + ""}>
                  <ProductCard product={product} />
                </Grid>
              );
            })}
            {productData.count > 0 ? (
              <Grid item xs={12}>
                <Pagination
                  count={Math.ceil(productData.count / 12)}
                  sx={{ ul: { justifyContent: "center" } }}
                  variant="outlined"
                  shape="rounded"
                  showLastButton
                  showFirstButton
                  page={router.query.p ? +router.query.p : 1}
                />
              </Grid>
            ) : null}
          </Grid>
        </div>
      </>
    </AccountLayout>
  );
};

export default Wishlist;
